[Variables]
CPUTemp-SensorId=0xf0000501
CPUTemp-SensorInstance=0x0
CPUTemp-EntryId=0x1000003

RAMTemp-SensorId=0xf3000002
RAMTemp-SensorInstance=0x0
RAMTemp-EntryId=0x1000000

WaterTemp-SensorId=0xfc04a100
WaterTemp-SensorInstance=0x30
WaterTemp-EntryId=0x1000000

GPUTemp-SensorId=0xe0002000
GPUTemp-SensorInstance=0x0
GPUTemp-EntryId=0x1000000

SSDTemp-SensorId=0xf0000100
SSDTemp-SensorInstance=0x0
SSDTemp-EntryId=0x1000000

MotherboardTemp-SensorId=0xf7067980
MotherboardTemp-SensorInstance=0x0
MotherboardTemp-EntryId=0x1000000

ChipsetTemp-SensorId=0xf0ec0502
ChipsetTemp-SensorInstance=0x0
ChipsetTemp-EntryId=0x1000001

VRMTemp-SensorId=0xf0ec0502
VRMTemp-SensorInstance=0x0
VRMTemp-EntryId=0x1000000

GPUFanSpeed-SensorId=0xe0002000
GPUFanSpeed-SensorInstance=0x0
GPUFanSpeed-EntryId=0x3000000

PumpSpeed-SensorId=0xfc04a100
PumpSpeed-SensorInstance=0x30
PumpSpeed-EntryId=0x3000002

RadiatorFanSpeed-SensorId=0xfc04a100
RadiatorFanSpeed-SensorInstance=0x30
RadiatorFanSpeed-EntryId=0x3000000

ChipsetFanSpeed-SensorId=0xf0ec0502
ChipsetFanSpeed-SensorInstance=0x0
ChipsetFanSpeed-EntryId=0x3000002

CPUUsage-SensorId=0xf0000300
CPUUsage-SensorInstance=0x0
CPUUsage-EntryId=0x7000021

GPUUsage-SensorId=0xe0002000
GPUUsage-SensorInstance=0x0
GPUUsage-EntryId=0x7000000

CPUPower-SensorId=0xf0000501
CPUPower-SensorInstance=0x0
CPUPower-EntryId=0x5000000

GPUPower-SensorId=0xe0002000
GPUPower-SensorInstance=0x0
GPUPower-EntryId=0x5000000

FrameRate-SensorId=0xf00f5000
FrameRate-SensorInstance=0x0
FrameRate-EntryId=0x8000000

[HWINFO-Config-FRAME RATE]
FrameRate=Frame Rate

[HWINFO-Config-USAGE]
CPUUsage=CPU
GPUUsage=GPU

[HWINFO-Config-TEMPERATURES]
CPUTemp=CPU
GPUTemp=GPU
RAMTemp=RAM
SSDTemp=SSD
VRMTemp=VRM
ChipsetTemp=Chipset
MotherboardTemp=Motherboard
WaterTemp=Water

[HWINFO-Config-FAN SPEEDS]
GPUFanSpeed=GPU
PumpSpeed=Pump
RadiatorFanSpeed=Radiator
ChipsetFanSpeed=Chipset

[HWINFO-Config-POWER]
CPUPower=CPU
GPUPower=GPU

