[Variables]
CPUTemp-SensorId=0xf0000501
CPUTemp-SensorInstance=0x0
CPUTemp-EntryId=0x1000003

RAMTemp-SensorId=0xf3000002
RAMTemp-SensorInstance=0x0
RAMTemp-EntryId=0x1000000

WaterTemp-SensorId=0xfc04a100
WaterTemp-SensorInstance=0x30
WaterTemp-EntryId=0x1000000

GPUTemp-SensorId=0xe0002000
GPUTemp-SensorInstance=0x0
GPUTemp-EntryId=0x1000000

SSDTemp-SensorId=0xf0000100
SSDTemp-SensorInstance=0x0
SSDTemp-EntryId=0x1000000

PumpSpeed-SensorId=0xfc04a100
PumpSpeed-SensorInstance=0x30
PumpSpeed-EntryId=0x3000002

[HWINFO-Config-TEMPERATURES]
CPUTemp=CPU
GPUTemp=GPU
RAMTemp=RAM
SSDTemp=SSD
WaterTemp=Water

[HWINFO-Config-FAN SPEEDS]
PumpSpeed=Pump




